# Shared Dakota kernel capabilities, applied after fdsdk-config.sh (and the
# OGC fragments on gaming builds). Keep this file shared with next: kernel
# versions and vendored upstream configuration remain stream-specific.
# Uses config-utils.sh enable/module so every option lands in
# expected-configs and the post-olddefconfig gate verifies it survived.

# Libvirt's nftables backend uses HTB + u32 + csum for DHCP checksum repair,
# even without configured bandwidth limits. The remaining options support
# libvirt's inbound/outbound bandwidth controls. No queue defaults change.
# https://github.com/libvirt/libvirt/blob/v12.7.0/src/network/network_nftables.c
# https://github.com/libvirt/libvirt/blob/v12.7.0/src/util/virnetdevbandwidth.c
# Request the parent menus explicitly rather than relying on arch defconfig.
enable NET_SCHED
enable NET_CLS_ACT
module NET_SCH_HTB
module NET_CLS_U32
module NET_ACT_CSUM
module NET_SCH_SFQ
module NET_CLS_FW
module NET_SCH_INGRESS
module NET_ACT_POLICE

# Make existing libvirt/Podman direct-LAN modes available; do not create
# interfaces or change the default networking mode.
module MACVLAN
module MACVTAP

# UAS-capable USB disks can use queued I/O instead of bulk-only transport.
module USB_UAS

# Allow cgroup disk-rate limits without imposing any limits by default.
enable BLK_DEV_THROTTLING

# The OGC fragment requests the timer trigger, but olddefconfig drops it
# unless IIO_SW_TRIGGER is enabled. Register both as expected capabilities
# on both kernels; these modules do not create or activate a sensor trigger.
module IIO_SW_TRIGGER
module IIO_HRTIMER_TRIGGER

# IPU7 lives in drivers/staging/media; these open the menu (they build
# nothing by themselves, staging drivers still need explicit enables).
enable STAGING
enable STAGING_MEDIA

# The power/GPIO half of the Intel IPU camera stack (audit found IPU6 shipped
# without it, so laptop MIPI webcams could not probe). Lives outside the
# audit's bucket regexes, hence listed here explicitly.
module INTEL_SKL_INT3472

enable ATH10K_DEBUGFS
module ATH10K_SDIO
enable FUSION
module FUSION_CTL
enable FUSION_LOGGING
# FUSION_MAX_SGE=128 skipped: int tunable already at upstream default
module FUSION_SAS
module FUSION_SPI
module HID_APPLE
enable HID_BPF
module HID_CHICONY
module HID_GOODIX_SPI
enable HID_HAPTIC
module HID_ITE
module HID_MICROSOFT
module HID_RAZER
module HID_SENSOR_PROX
module HYPERV_VSOCKETS
module MEGARAID_MAILBOX
module MEGARAID_MM
enable MEGARAID_NEWGEN
module MEGARAID_SAS
module MT7663S
module PATA_ACPI
module PATA_ALI
module PATA_ARTOP
module PATA_ATIIXP
module PATA_ATP867X
module PATA_CMD64X
module PATA_HPT366
module PATA_HPT37X
module PATA_HPT3X2N
module PATA_HPT3X3
module PATA_IT8213
module PATA_IT821X
module PATA_JMICRON
module PATA_MARVELL
module PATA_NETCELL
module PATA_NINJA32
module PATA_PCMCIA
module PATA_PDC2027X
module PATA_PDC_OLD
module PATA_SERVERWORKS
module PATA_SIL680
module PATA_SIS
module PATA_VIA
enable RTL8XXXU_UNTESTED
module RTW89_8852AU
module RTW89_8852CU
module SATA_AHCI_PLATFORM
module SATA_MV
module SATA_NV
module SATA_PROMISE
module SATA_SIL24
module SATA_SIL
module SATA_SIS
module SATA_ULI
module SATA_VIA
module SCSI_3W_9XXX
module SCSI_3W_SAS
module SCSI_AACRAID
module SCSI_AIC79XX
module SCSI_AIC7XXX
module SCSI_AM53C974
module SCSI_ARCMSR
module SCSI_BUSLOGIC
module SCSI_ESAS2R
module SCSI_HPSA
module SCSI_ISCI
# SCSI_MPT2SAS_MAX_SGE=128 skipped: int tunable already at upstream default
module SCSI_MPT3SAS
# SCSI_MPT3SAS_MAX_SGE=128 skipped: int tunable already at upstream default
module SCSI_MVSAS
module SCSI_PM8001
module SCSI_SMARTPQI
module SCSI_STEX
module SENSORS_ASUS_ROG_RYUJIN
module SENSORS_GIGABYTE_WATERFORCE
module SENSORS_NZXT_KRAKEN2
module SENSORS_NZXT_KRAKEN3
module SENSORS_NZXT_SMART2
module SENSORS_SURFACE_FAN
module SENSORS_SURFACE_TEMP
module SENSORS_YOGAFAN
module SND_AMD_ASOC_ACP63
module SND_AMD_ASOC_REMBRANDT
module SND_AMD_ASOC_RENOIR
module SND_HDA_CODEC_CM9825
module SND_HDA_CODEC_SENARYTECH
enable SND_HDA_INTEL_HDMI_SILENT_STREAM
module SND_HDA_SCODEC_TAS2781_SPI
enable SND_SEQ_UMP
module SND_SEQ_UMP_CLIENT
module SND_SOC_AMD_ACP_PCI
module SND_SOC_SOF_AMD_ACP70
module SND_SOC_SOF_AMD_RENOIR
module SND_UMP
enable SND_UMP_LEGACY_RAWMIDI
enable SND_USB_AUDIO_MIDI_V2
module TOUCHSCREEN_CHIPONE_ICN8505
enable TOUCHSCREEN_DMI
module TOUCHSCREEN_ELAN
module USB_XEN_HCD
module VBOXSF_FS
module VIDEO_HI846
module VIDEO_HI847
module VIDEO_IMX208
module VIDEO_IMX319
module VIDEO_IMX355
module VIDEO_INTEL_IPU7
module VIDEO_OG01A1B
module VIDEO_OV02C10
module VIDEO_OV02E10
module VIDEO_OV08D10
module VIDEO_OV5675
module VIDEO_OV9734
module VMWARE_VMCI_VSOCKETS
module VMXNET3
enable XEN_GRANT_DMA_OPS
enable XEN_PVH
enable XEN_VIRTIO
module XEN_WDT

# Compress modules at install time with the elements' ZSTD_CLEVEL.
enable MODULE_COMPRESS
enable MODULE_COMPRESS_ZSTD
enable MODULE_COMPRESS_ALL

# Broad hardware coverage so unusual hardware works without per-device
# requests; unused modules never load. Excludes test drivers, OGC's unset
# options and INPUT_PCSPKR (collides with fdsdk's SND_PCSP). Each line must
# survive olddefconfig on both kernels or the expected-configs gate fails.
# Side effect: HYPERV_STORAGE and I3C_OR_I2C become modules (the initramfs
# carries drivers/scsi). x86_64 only.
if [ "${ARCH}" = x86_64 ]; then
  # arch/x86
  module CRYPTO_AEGIS128_AESNI_SSE2
  module CRYPTO_BLOWFISH_X86_64
  module CRYPTO_CAMELLIA_AESNI_AVX2_X86_64
  module CRYPTO_CAMELLIA_AESNI_AVX_X86_64
  module CRYPTO_CAMELLIA_X86_64
  module CRYPTO_CAST5_AVX_X86_64
  module CRYPTO_CAST6_AVX_X86_64
  module CRYPTO_SERPENT_AVX2_X86_64
  module CRYPTO_SERPENT_AVX_X86_64
  module CRYPTO_SERPENT_SSE2_X86_64
  module CRYPTO_TWOFISH_AVX_X86_64
  module CRYPTO_TWOFISH_X86_64
  module CRYPTO_TWOFISH_X86_64_3WAY
  module X86_MCE_INJECT
  module X86_PMEM_LEGACY
  # crypto
  module CRYPTO_BENCHMARK
  module CRYPTO_HCTR2
  # crypto/asymmetric_keys
  module PKCS8_PRIVATE_KEY_PARSER
  # drivers/acpi
  module ACPI_APEI_GHES_NVIDIA
  module ACPI_NFIT
  # drivers/ata
  module AHCI_DWC
  module ATA_GENERIC
  module PATA_CMD640_PCI
  module PATA_EFAR
  module PATA_MPIIX
  module PATA_NS87410
  module PATA_NS87415
  module PATA_OPTI
  module PATA_OPTIDMA
  module PATA_TOSHIBA
  module PATA_TRIFLEX
  module PATA_WINBOND
  module PDC_ADMA
  module SATA_ACARD_AHCI
  module SATA_INIC162X
  module SATA_QSTOR
  module SATA_SVW
  module SATA_SX4
  module SATA_VITESSE
  # drivers/atm
  module ATM_SOLOS
  # drivers/block
  module ATA_OVER_ETH
  module BLK_DEV_DRBD
  module BLK_DEV_FD
  module BLK_DEV_NULL_BLK
  module BLK_DEV_PCIESSD_MTIP32XX
  module BLK_DEV_RBD
  module BLK_DEV_RNBD_CLIENT
  module BLK_DEV_RNBD_SERVER
  module BLK_DEV_RUST_NULL
  module BLK_DEV_UBLK
  module XEN_BLKDEV_BACKEND
  # drivers/bus
  module MHI_BUS_PCI_GENERIC
  # drivers/char
  module HANGCHECK_TIMER
  module HW_RANDOM_TIMERIOMEM
  module HW_RANDOM_XIPHERA
  module IPMI_DEVICE_INTERFACE
  module IPMI_IPMB
  module IPMI_POWEROFF
  module IPMI_SSIF
  module IPMI_WATCHDOG
  module PPDEV
  module PRINTER
  module SSIF_IPMI_BMC
  module TCG_ATMEL
  module TCG_INFINEON
  module TCG_NSC
  module TCG_TIS_I2C
  module TCG_TIS_I2C_ATMEL
  module TCG_TIS_I2C_CR50
  module TCG_TIS_I2C_INFINEON
  module TCG_TIS_I2C_NUVOTON
  module TCG_VTPM_PROXY
  module TELCLOCK
  module XILLYBUS
  module XILLYBUS_PCIE
  module XILLYUSB
  # drivers/clk
  module COMMON_CLK_SI544
  module COMMON_CLK_TPS68470
  module XILINX_VCU
  # drivers/counter
  module COUNTER
  module INTEL_QEP
  # drivers/crypto
  module CRYPTO_DEV_ATMEL_ECC
  module CRYPTO_DEV_ATMEL_SHA204A
  module CRYPTO_DEV_CHELSIO
  module CRYPTO_DEV_IAA_CRYPTO
  module CRYPTO_DEV_NITROX_CNN55XX
  module CRYPTO_DEV_PADLOCK
  module CRYPTO_DEV_PADLOCK_AES
  module CRYPTO_DEV_PADLOCK_SHA
  module CRYPTO_DEV_QAT_420XX
  module CRYPTO_DEV_QAT_4XXX
  module CRYPTO_DEV_QAT_6XXX
  module CRYPTO_DEV_QAT_C3XXX
  module CRYPTO_DEV_QAT_C3XXXVF
  module CRYPTO_DEV_QAT_C62X
  module CRYPTO_DEV_QAT_C62XVF
  module CRYPTO_DEV_QAT_DH895xCC
  module CRYPTO_DEV_QAT_DH895xCCVF
  # drivers/cxl
  module CXL_ACPI
  module CXL_BUS
  module CXL_MEM
  module CXL_PCI
  module CXL_PMEM
  # drivers/dax
  module DEV_DAX
  module DEV_DAX_CXL
  module DEV_DAX_HMEM
  module DEV_DAX_KMEM
  # drivers/devfreq
  module DEVFREQ_GOV_SIMPLE_ONDEMAND
  # drivers/dibs
  module DIBS
  # drivers/dma
  module ALTERA_MSGDMA
  module AMD_AE4DMA
  module AMD_QDMA
  module DW_DMAC
  module DW_EDMA
  module DW_EDMA_PCIE
  module INTEL_IDMA64
  module INTEL_IDXD
  module INTEL_IOATDMA
  module XILINX_XDMA
  # drivers/dpll
  module ZL3073X
  module ZL3073X_I2C
  module ZL3073X_SPI
  # drivers/edac
  module EDAC_IMH
  # drivers/extcon
  module EXTCON_INTEL_INT3496
  module EXTCON_INTEL_MRFLD
  module EXTCON_LC824206XA
  module EXTCON_USBC_CROS_EC
  module EXTCON_USBC_TUSB320
  # drivers/firmware
  module EDD
  module ISCSI_IBFT
  # drivers/fpga
  module ALTERA_PR_IP_CORE
  module FPGA
  module FPGA_BRIDGE
  module FPGA_DFL
  module FPGA_DFL_AFU
  module FPGA_DFL_FME
  module FPGA_DFL_FME_BRIDGE
  module FPGA_DFL_FME_MGR
  module FPGA_DFL_FME_REGION
  module FPGA_DFL_NIOS_INTEL_PAC_N3000
  module FPGA_DFL_PCI
  module FPGA_M10_BMC_SEC_UPDATE
  module FPGA_MGR_ALTERA_CVP
  module FPGA_MGR_ALTERA_PS_SPI
  module FPGA_MGR_EFINIX_SPI
  module FPGA_MGR_LATTICE_SYSCONFIG_SPI
  module FPGA_MGR_MACHXO2_SPI
  module FPGA_MGR_XILINX_SELECTMAP
  module FPGA_MGR_XILINX_SPI
  module FPGA_REGION
  module XILINX_PR_DECOUPLER
  # drivers/fwctl
  module FWCTL
  module FWCTL_BNXT
  module FWCTL_MLX5
  module FWCTL_PDS
  # drivers/gnss
  module GNSS
  module GNSS_MTK_SERIAL
  module GNSS_SIRF_SERIAL
  module GNSS_UBX_SERIAL
  module GNSS_USB
  # drivers/gpib
  module GPIB
  module GPIB_AGILENT_82350B
  module GPIB_AGILENT_82357A
  module GPIB_CB7210
  module GPIB_CEC_PCI
  module GPIB_COMMON
  module GPIB_INES
  module GPIB_LPVO
  module GPIB_NI_PCI_ISA
  module GPIB_NI_USB
  # drivers/gpio
  module GPIO_AGGREGATOR
  module GPIO_ARIZONA
  module GPIO_BD9571MWV
  module GPIO_BT8XX
  module GPIO_BY_PINCTRL
  module GPIO_CGBC
  module GPIO_CROS_EC
  module GPIO_DLN2
  module GPIO_DS4520
  module GPIO_ELKHARTLAKE
  module GPIO_EXAR
  module GPIO_FXL6408
  module GPIO_GRANITERAPIDS
  module GPIO_ICH
  module GPIO_IT87
  module GPIO_LJCA
  module GPIO_MPSSE
  module GPIO_NOVALAKE
  module GPIO_PCA953X
  module GPIO_PCA9570
  module GPIO_PCI_IDIO_16
  module GPIO_QIXIS_FPGA
  module GPIO_SIM
  module GPIO_TPS68470
  module GPIO_USBIO
  module GPIO_VIRTIO
  module GPIO_VIRTUSER
  module GPIO_WHISKEY_COVE
  # drivers/gpu/drm
  module DRM_AST
  module DRM_BOCHS
  module DRM_CIRRUS_QEMU
  module DRM_GM12U320
  module DRM_GUD
  module DRM_I915_GVT_KVMGT
  module DRM_MGAG200
  module DRM_PANEL_FOCALTECH_OTA7290B
  module DRM_PANEL_MIPI_DBI
  module DRM_PANEL_WIDECHIPS_WS2401
  module DRM_PIXPAPER
  module DRM_QXL
  module DRM_SSD130X
  module DRM_SSD130X_I2C
  module DRM_SSD130X_SPI
  module DRM_ST7571
  module DRM_ST7571_I2C
  module DRM_ST7571_SPI
  module DRM_ST7586
  module DRM_ST7735R
  module DRM_ST7920
  module DRM_UDL
  module DRM_VGEM
  module DRM_VKMS
  module TINYDRM_ILI9163
  module TINYDRM_ILI9486
  module TINYDRM_SHARP_MEMORY
  # drivers/hid
  module HID_A4TECH
  module HID_BELKIN
  module HID_CHERRY
  module HID_CYPRESS
  module HID_EVISION
  module HID_EZKEY
  module HID_GOOGLE_STADIA_FF
  module HID_HUAWEI
  module HID_KENSINGTON
  module HID_KYSONA
  module HID_LENOVO_GO
  module HID_LENOVO_GO_S
  module HID_LETSKETCH
  module HID_MEGAWORLD_FF
  module HID_MONTEREY
  module HID_NVIDIA_SHIELD
  module HID_OXP
  module HID_PXRC
  module HID_RAKK
  module HID_RAPOO
  module HID_SIGMAMICRO
  module HID_TOPRE
  module HID_UNIVERSAL_PIDFF
  module HID_WINWING
  module HID_XIAOMI
  # drivers/hid/intel-ish-hid
  module INTEL_ISH_FIRMWARE_DOWNLOADER
  # drivers/hid/intel-thc-hid
  module INTEL_QUICKI2C
  module INTEL_QUICKSPI
  module INTEL_THC_HID
  # drivers/hv
  module MSHV_ROOT
  # drivers/hwmon
  module MAX31827
  module PMBUS
  module SENSORS_AD7314
  module SENSORS_ADC128D818
  module SENSORS_ADM1266
  module SENSORS_ADM1275
  module SENSORS_ADP1050
  module SENSORS_ADT7310
  module SENSORS_ADT7410
  module SENSORS_ARCTIC_FAN_CONTROLLER
  module SENSORS_AXI_FAN_CONTROL
  module SENSORS_BEL_PFE
  module SENSORS_BPA_RS600
  module SENSORS_CGBC
  module SENSORS_CHIPCAP2
  module SENSORS_CRPS
  module SENSORS_DELTA_AHE50DC_FAN
  module SENSORS_DPS920AB
  module SENSORS_EMC2305
  module SENSORS_FSP_3Y
  module SENSORS_G762
  module SENSORS_GPD
  module SENSORS_HAC300S
  module SENSORS_HS3001
  module SENSORS_HTU31
  module SENSORS_INA209
  module SENSORS_INA233
  module SENSORS_INA238
  module SENSORS_INA2XX
  module SENSORS_INA3221
  module SENSORS_INTEL_M10_BMC_HWMON
  module SENSORS_ISL28022
  module SENSORS_LATTEPANDA_SIGMA_EC
  module SENSORS_LENOVO_EC
  module SENSORS_LM25066
  module SENSORS_LM95234
  module SENSORS_LT3074
  module SENSORS_LT3074_REGULATOR
  module SENSORS_LT7182S
  module SENSORS_LTC2945
  module SENSORS_LTC2947_I2C
  module SENSORS_LTC2947_SPI
  module SENSORS_LTC2978
  module SENSORS_LTC2990
  module SENSORS_LTC2991
  module SENSORS_LTC3815
  module SENSORS_LTC4222
  module SENSORS_LTC4260
  module SENSORS_MAX16064
  module SENSORS_MAX17616
  module SENSORS_MAX197
  module SENSORS_MAX20751
  module SENSORS_MAX31722
  module SENSORS_MAX31760
  module SENSORS_MAX31790
  module SENSORS_MAX34440
  module SENSORS_MAX6620
  module SENSORS_MAX6697
  module SENSORS_MAX77705
  module SENSORS_MAX8688
  module SENSORS_MC34VR500
  module SENSORS_MCP3021
  module SENSORS_MCP9982
  module SENSORS_MLXREG_FAN
  module SENSORS_MP2869
  module SENSORS_MP2888
  module SENSORS_MP2891
  module SENSORS_MP2925
  module SENSORS_MP29502
  module SENSORS_MP2975
  module SENSORS_MP2993
  module SENSORS_MP5023
  module SENSORS_MP5920
  module SENSORS_MP5926
  module SENSORS_MP9941
  module SENSORS_MP9945
  module SENSORS_MPQ7932
  module SENSORS_MPQ8785
  module SENSORS_MR75203
  module SENSORS_NCT6775_I2C
  module SENSORS_NCT7363
  module SENSORS_PIM4328
  module SENSORS_PLI1209BC
  module SENSORS_PM6764TR
  module SENSORS_PMBUS
  module SENSORS_POWERZ
  module SENSORS_POWR1220
  module SENSORS_PT5161L
  module SENSORS_PWM_FAN
  module SENSORS_Q54SJ108A2
  module SENSORS_QNAP_MCU_HWMON
  module SENSORS_SBTSI
  module SENSORS_SHT15
  module SENSORS_SHTC1
  module SENSORS_STEF48H28
  module SENSORS_SY7636A
  module SENSORS_TC654
  module SENSORS_TC74
  module SENSORS_TDA38640
  module SENSORS_TMP103
  module SENSORS_TMP108
  module SENSORS_TMP464
  module SENSORS_TMP513
  module SENSORS_TPS25990
  module SENSORS_TPS40422
  module SENSORS_TPS53679
  module SENSORS_TPS546D24
  module SENSORS_TSC1641
  module SENSORS_UCD9000
  module SENSORS_UCD9200
  module SENSORS_XDP710
  module SENSORS_XDPE152
  module SENSORS_ZL6100
  # drivers/hwtracing
  module INTEL_TH
  module INTEL_TH_ACPI
  module INTEL_TH_GTH
  module INTEL_TH_MSU
  module INTEL_TH_PCI
  module INTEL_TH_PTI
  module INTEL_TH_STH
  module STM
  module STM_DUMMY
  module STM_PROTO_BASIC
  module STM_PROTO_SYS_T
  module STM_SOURCE_CONSOLE
  module STM_SOURCE_FTRACE
  module STM_SOURCE_HEARTBEAT
  # drivers/i2c
  module I2C_AMD_ASF
  module I2C_ATR
  module I2C_CGBC
  module I2C_CP2615
  module I2C_DLN2
  module I2C_LJCA
  module I2C_MLXCPLD
  module I2C_MUX_LTC4306
  module I2C_MUX_MLXCPLD
  module I2C_MUX_PCA954x
  module I2C_NVIDIA_GPU
  module I2C_PCI1XXXX
  module I2C_SLAVE_EEPROM
  module I2C_USBIO
  module I2C_ZHAOXIN
  # drivers/i3c
  module ADI_I3C_MASTER
  module CDNS_I3C_MASTER
  module DW_I3C_MASTER
  module I3C
  module MIPI_I3C_HCI
  module MIPI_I3C_HCI_PCI
  module SVC_I3C_MASTER
  # drivers/iio
  module ABP2030PA_I2C
  module ABP2030PA_SPI
  module AD3530R
  module AD3552R
  module AD3552R_HS
  module AD4000
  module AD4030
  module AD4062
  module AD4080
  module AD4130
  module AD4134
  module AD4170_4
  module AD4691
  module AD4695
  module AD4851
  module AD5110
  module AD5272
  module AD5706R
  module AD5766
  module AD7091R8
  module AD7191
  module AD7293
  module AD7380
  module AD7405
  module AD74115
  module AD74413R
  module AD7625
  module AD7779
  module AD8460
  module AD9467
  module ADE9000
  module ADF4377
  module ADIS16550
  module ADL8113
  module ADXL380_I2C
  module ADXL380_SPI
  module AL3000A
  module AL3320A
  module APDS9160
  module APDS9306
  module APDS9999
  module BD79703
  module BH1745
  module BMC150_MAGN_SPI
  module BME680
  module BMI160_I2C
  module BMI160_SPI
  module BMI270_I2C
  module BMI270_SPI
  module BMI323_I2C
  module BOSCH_BNO055_I2C
  module BOSCH_BNO055_SERIAL
  module CM3605
  module CROS_EC_MKBP_PROXIMITY
  module D3323AA
  module DHT11
  module DLN2_ADC
  module DPOT_DAC
  module ENVELOPE_DETECTOR
  module HDC2010
  module HID_SENSOR_CUSTOM_INTEL_HINGE
  module HID_SENSOR_HUMIDITY
  module HMC425
  module HTS221
  module IIO_BUFFER_CB
  module IIO_BUFFER_HW_CONSUMER
  module IIO_CROS_EC_ACTIVITY
  module IIO_MUX
  module IIO_RESCALE
  module IIO_ST_LSM6DSX_I3C
  module IIO_ST_LSM9DS0
  module IIO_ST_LSM9DS0_I2C
  module IIO_SW_DEVICE
  module IIO_TIGHTLOOP_TRIGGER
  module IIO_TRIGGERED_EVENT
  module INTEL_DC_TI_ADC
  module INTEL_MRFLD_ADC
  module INV_ICM45600_I2C
  module INV_ICM45600_I3C
  module INV_ICM45600_SPI
  module LMP91000
  module LTC2664
  module LTC2688
  module LTRF216A
  module MAX11205
  module MAX11410
  module MAX14001
  module MAX22007
  module MAX30100
  module MAX30208
  module MAX31865
  module MAX34408
  module MAX5522
  module MCP4018
  module MCP41010
  module MCP4728
  module MCP47FEB02
  module MCP4821
  module MCP9600
  module MMC5633
  module MMC5983
  module MPRLS0025PA
  module MPRLS0025PA_I2C
  module MPRLS0025PA_SPI
  module OPT4001
  module OPT4060
  module PAC1921
  module PAC1934
  module PMS7003
  module RICHTEK_RTQ6056
  module ROHM_BD79124
  module ROHM_BU27034
  module SCD30_CORE
  module SCD30_I2C
  module SCD30_SERIAL
  module SD_ADC_MODULATOR
  module SMI330_I2C
  module SMI330_SPI
  module SX9324
  module SX9360
  module TI_ADS1018
  module TI_ADS1100
  module TI_ADS131E08
  module TI_ADS131M02
  module TI_ADS7138
  module TI_ADS7924
  module TI_ADS8344
  module TI_LMP92064
  module TI_TSC2046
  module TMP117
  module VEML3235
  module VEML3328
  module VL53L1X_I2C
  module X9250
  # drivers/infiniband
  module INFINIBAND
  module INFINIBAND_CXGB4
  module INFINIBAND_EFA
  module INFINIBAND_ERDMA
  module INFINIBAND_HFI1
  module INFINIBAND_IONIC
  module INFINIBAND_IPOIB
  module INFINIBAND_IRDMA
  module INFINIBAND_ISER
  module INFINIBAND_ISERT
  module INFINIBAND_MTHCA
  module INFINIBAND_OCRDMA
  module INFINIBAND_QEDR
  module INFINIBAND_RDMAVT
  module INFINIBAND_RTRS_CLIENT
  module INFINIBAND_RTRS_SERVER
  module INFINIBAND_SRP
  module INFINIBAND_SRPT
  module INFINIBAND_USER_ACCESS
  module INFINIBAND_USER_MAD
  module INFINIBAND_USNIC
  module INFINIBAND_VMWARE_PVRDMA
  module MANA_INFINIBAND
  module MLX4_INFINIBAND
  module MLX5_INFINIBAND
  module RDMA_RXE
  module RDMA_SIW
  # drivers/input
  module INPUT_MATRIXKMAP
  # drivers/input/joystick
  module JOYSTICK_ADC
  module JOYSTICK_PSXPAD_SPI
  module JOYSTICK_QWIIC
  # drivers/input/keyboard
  module KEYBOARD_CHARLIEPLEX
  module KEYBOARD_CROS_EC
  module KEYBOARD_CYPRESS_SF
  module KEYBOARD_QT1050
  module KEYBOARD_QT1070
  module KEYBOARD_TM2_TOUCHKEY
  # drivers/input/misc
  module INPUT_APANEL
  module INPUT_ATI_REMOTE2
  module INPUT_ATLAS_BTNS
  module INPUT_AXP20X_PEK
  module INPUT_CM109
  module INPUT_CMA3000
  module INPUT_CMA3000_I2C
  module INPUT_CS40L50_VIBRA
  module INPUT_E3X0_BUTTON
  module INPUT_GPIO_BEEPER
  module INPUT_GPIO_ROTARY_ENCODER
  module INPUT_GPIO_VIBRA
  module INPUT_IDEAPAD_SLIDEBAR
  module INPUT_IQS269A
  module INPUT_IQS626A
  module INPUT_IQS7222
  module INPUT_KEYSPAN_REMOTE
  module INPUT_KXTJ9
  module INPUT_MAX77693_HAPTIC
  module INPUT_POWERMATE
  module INPUT_PWM_BEEPER
  module INPUT_QNAP_MCU
  module INPUT_RT5120_PWRKEY
  module INPUT_TPS6594_PWRBUTTON
  module INPUT_YEALINK
  # drivers/input/rmi4
  module RMI4_SMB
  module RMI4_SPI
  # drivers/input/serio
  module SERIO_ALTERA_PS2
  module SERIO_ARC_PS2
  module SERIO_RAW
  # drivers/input/touchscreen
  module TOUCHSCREEN_AUO_PIXCIR
  module TOUCHSCREEN_COLIBRI_VF50
  module TOUCHSCREEN_CY8CTMA140
  module TOUCHSCREEN_CYTTSP5
  module TOUCHSCREEN_EDT_FT5X06
  module TOUCHSCREEN_EGALAX_SERIAL
  module TOUCHSCREEN_HIDEEP
  module TOUCHSCREEN_HIMAX_HX83112B
  module TOUCHSCREEN_HIMAX_HX852X
  module TOUCHSCREEN_HYCON_HY46XX
  module TOUCHSCREEN_HYNITRON_CST816X
  module TOUCHSCREEN_HYNITRON_CSTXXX
  module TOUCHSCREEN_ILI210X
  module TOUCHSCREEN_ILITEK
  module TOUCHSCREEN_IMAGIS
  module TOUCHSCREEN_IQS5XX
  module TOUCHSCREEN_IQS7211
  module TOUCHSCREEN_MMS114
  module TOUCHSCREEN_MSG2638
  module TOUCHSCREEN_NOVATEK_NVT_TS
  module TOUCHSCREEN_PIXCIR
  module TOUCHSCREEN_RM_TS
  module TOUCHSCREEN_SIS_I2C
  module TOUCHSCREEN_ST1232
  module TOUCHSCREEN_WACOM_I2C
  module TOUCHSCREEN_WACOM_W9000
  module TOUCHSCREEN_ZET6223
  module TOUCHSCREEN_ZFORCE
  module TOUCHSCREEN_ZINITIX
  # drivers/leds
  module LEDS_AS3645A
  module LEDS_AW200XX
  module LEDS_BLINKM
  module LEDS_CHT_WCOVE
  module LEDS_KTD202X
  module LEDS_LM3530
  module LEDS_LM3532
  module LEDS_LM3601X
  module LEDS_LP3952
  module LEDS_LP50XX
  module LEDS_LP5812
  module LEDS_MAX5970
  module LEDS_MAX77705
  module LEDS_MLXCPLD
  module LEDS_MLXREG
  module LEDS_NIC78BX
  module LEDS_OSRAM_AMS_AS3668
  module LEDS_PCA9532
  module LEDS_PCA995X
  module LEDS_PWM_MULTICOLOR
  module LEDS_QNAP_MCU
  module LEDS_TRIGGER_GPIO
  module LEDS_TRIGGER_INPUT_EVENTS
  module LEDS_TRIGGER_TTY
  module LEDS_UPBOARD
  module LEDS_USER
  # drivers/md
  module BCACHE
  module DM_CACHE
  module DM_CACHE_SMQ
  module DM_CLONE
  module DM_DELAY
  module DM_DUST
  module DM_EBS
  module DM_ERA
  module DM_FLAKEY
  module DM_LOG_USERSPACE
  module DM_LOG_WRITES
  module DM_MULTIPATH
  module DM_MULTIPATH_HST
  module DM_MULTIPATH_IOA
  module DM_MULTIPATH_QL
  module DM_MULTIPATH_ST
  module DM_SWITCH
  module DM_THIN_PROVISIONING
  module DM_UNSTRIPED
  module DM_VDO
  module DM_WRITECACHE
  module MD_LINEAR
  # drivers/media/cec
  module CEC_CH7322
  module CEC_GPIO
  module CEC_NXP_TDA9950
  module CEC_SECO
  module USB_PULSE8_CEC
  module USB_RAINSHADOW_CEC
  # drivers/media/i2c
  module VIDEO_AD5820
  module VIDEO_ADP1653
  module VIDEO_AK7375
  module VIDEO_AR0521
  module VIDEO_CCS
  module VIDEO_DW9714
  module VIDEO_DW9719
  module VIDEO_DW9768
  module VIDEO_DW9807_VCM
  module VIDEO_ET8EK8
  module VIDEO_GC0308
  module VIDEO_GC0310
  module VIDEO_GC2145
  module VIDEO_IMX111
  module VIDEO_IMX214
  module VIDEO_IMX219
  module VIDEO_IMX258
  module VIDEO_IMX274
  module VIDEO_IMX283
  module VIDEO_IMX290
  module VIDEO_IMX296
  module VIDEO_LM3560
  module VIDEO_LM3646
  module VIDEO_MAX96717
  module VIDEO_MSP3400
  module VIDEO_MT9M001
  module VIDEO_MT9M114
  module VIDEO_MT9P031
  module VIDEO_MT9T112
  module VIDEO_MT9V011
  module VIDEO_MT9V111
  module VIDEO_OG0VE1B
  module VIDEO_OS05B10
  module VIDEO_OV02A10
  module VIDEO_OV13858
  module VIDEO_OV2640
  module VIDEO_OV2659
  module VIDEO_OV2685
  module VIDEO_OV2735
  module VIDEO_OV4689
  module VIDEO_OV5647
  module VIDEO_OV5648
  module VIDEO_OV5695
  module VIDEO_OV6211
  module VIDEO_OV64A40
  module VIDEO_OV7640
  module VIDEO_OV772X
  module VIDEO_OV7740
  module VIDEO_OV8858
  module VIDEO_OV9640
  module VIDEO_OV9650
  module VIDEO_RDACM20
  module VIDEO_RJ54N1
  module VIDEO_S5C73M3
  module VIDEO_S5K3M5
  module VIDEO_S5K5BAF
  module VIDEO_S5K6A3
  module VIDEO_S5KJN1
  module VIDEO_SAA711X
  module VIDEO_T4KA3
  module VIDEO_TVP5150
  module VIDEO_VD55G1
  module VIDEO_VD56G3
  # drivers/media/pci
  module INTEL_VSC
  module VIDEO_HWS
  module VIDEO_SOLO6X10
  module VIDEO_TW686X
  # drivers/media/radio
  module I2C_SI470X
  module RADIO_MAXIRADIO
  module RADIO_SAA7706H
  module RADIO_SHARK
  module RADIO_SHARK2
  module RADIO_SI470X
  module RADIO_SI4713
  module RADIO_TEA5764
  module USB_DSBR
  module USB_KEENE
  module USB_MA901
  module USB_MR800
  module USB_SI470X
  # drivers/media/spi
  module VIDEO_GS1662
  # drivers/media/usb
  module USB_GL860
  module USB_M5602
  module USB_S2255
  module USB_STV06XX
  module VIDEO_EM28XX
  module VIDEO_EM28XX_ALSA
  module VIDEO_EM28XX_RC
  module VIDEO_EM28XX_V4L2
  module VIDEO_USBTV
  # drivers/media/v4l2-core
  module VIDEO_TUNER
  # drivers/memstick
  module MEMSTICK
  module MEMSTICK_JMICRON_38X
  module MEMSTICK_R592
  module MEMSTICK_REALTEK_USB
  module MEMSTICK_TIFM_MS
  module MSPRO_BLOCK
  # drivers/message
  module FUSION_FC
  # drivers/mfd
  module INTEL_SOC_PMIC_MRFLD
  module MFD_ARIZONA_SPI
  module MFD_BD9571MWV
  module MFD_CGBC
  module MFD_CS40L50_I2C
  module MFD_CS40L50_SPI
  module MFD_CS42L43_I2C
  module MFD_DLN2
  module MFD_INTEL_M10_BMC_PMCI
  module MFD_INTEL_M10_BMC_SPI
  module MFD_MAX5970
  module MFD_MAX77705
  module MFD_QNAP_MCU
  module MFD_RT4831
  module MFD_RT5120
  module MFD_SIMPLE_MFD_I2C
  module MFD_SM501
  module MFD_SY7636A
  module MFD_TPS6594_I2C
  module MFD_UPBOARD_FPGA
  module MFD_VX855
  # drivers/misc
  module ALTERA_STAPL
  module APDS9802ALS
  module BCM_VK
  module DW_XDATA_PCIE
  module EEPROM_AT24
  module EEPROM_EE1004
  module EEPROM_IDT_89HPESX
  module EEPROM_M24LR
  module EEPROM_MAX6875
  module ENCLOSURE_SERVICES
  module GP_PCI1XXXX
  module HP_ILO
  module IBM_ASM
  module INTEL_MEI_CSC
  module INTEL_MEI_GSC
  module INTEL_MEI_GSC_PROXY
  module INTEL_MEI_HDCP
  module INTEL_MEI_LB
  module INTEL_MEI_PXP
  module INTEL_MEI_TXE
  module INTEL_MEI_VSC
  module INTEL_MEI_VSC_HW
  module ISL29003
  module ISL29020
  module MISC_ALCOR_PCI
  module NSM
  module RPMB
  module SENSORS_BH1770
  module SENSORS_LIS3_I2C
  module SENSORS_TSL2550
  module TI_FPC202
  module TPS6594_ESM
  module TPS6594_PFSM
  module UACCE
  # drivers/mmc
  module MMC_ALCOR
  module MMC_HSQ
  module MMC_SDHCI_PLTFM
  module MMC_SDHCI_XENON
  # drivers/mtd
  module MTD_BLKDEVS
  module MTD_BLOCK
  module MTD_BLOCK2MTD
  module MTD_INTEL_DG
  module MTD_MCHP48L640
  module MTD_MTDRAM
  module MTD_NAND_NANDSIM
  module MTD_RAW_NAND
  module MTD_SPI_NOR
  module MTD_UBI
  module MTD_UBI_NVMEM
  # drivers/mux
  module MUX_ADG792A
  module MUX_GPIO
  # drivers/net
  module AMT
  module BAREUDP
  module BONDING
  module EQUALIZER
  module FUJITSU_ES
  module GENEVE
  module GTP
  module IFB
  module IPVTAP
  module MACSEC
  module MHI_NET
  module NET_VRF
  module NLMON
  module NTB_NETDEV
  module OVPN
  module PFCP
  module VSOCKMON
  module VXLAN
  module XEN_NETDEV_BACKEND
  # drivers/net/dsa
  module B53
  module B53_MDIO_DRIVER
  module B53_MMAP_DRIVER
  module B53_SERDES
  module B53_SPI_DRIVER
  module B53_SRAB_DRIVER
  module NET_DSA_BCM_SF2
  module NET_DSA_HIRSCHMANN_HELLCREEK
  module NET_DSA_LOOP
  module NET_DSA_MT7530
  module NET_DSA_MT7530_MDIO
  module NET_DSA_MT7530_MMIO
  module NET_DSA_MV88E6XXX
  module NET_DSA_MXL862
  module NET_DSA_QCA8K
  module NET_DSA_REALTEK
  module NET_DSA_SMSC_LAN9303_I2C
  module NET_DSA_SMSC_LAN9303_MDIO
  module NET_DSA_XRS700X_I2C
  module NET_DSA_XRS700X_MDIO
  # drivers/net/ethernet
  module ADIN1110
  module ALIBABA_EEA
  module ALTERA_TSE
  module BCMGENET
  module BNGE
  module CHELSIO_IPSEC_INLINE
  module DM9051
  module DWMAC_MOTORCOMM
  module ETHOC
  module FM10K
  module FUN_ETH
  module HIBMCGE
  module IDPF
  module IONIC
  module LAN743X
  module MACB
  module MACB_PCI
  module MLX5_DPLL
  module MLXSW_CORE
  module MLXSW_I2C
  module MLXSW_MINIMAL
  module MLXSW_PCI
  module MLXSW_SPECTRUM
  module MSE102X
  module MVMDIO
  module NGBE
  module NGBEVF
  module OCTEON_EP
  module OCTEON_EP_VF
  module PDS_CORE
  module PRESTERA
  module PRESTERA_PCI
  module SFC_SIENA
  module SMSC911X
  module SPI_AX88796C
  module SUNDANCE
  module TEHUTI_TN40
  module TSNEP
  module TXGBE
  module TXGBEVF
  module WIZNET_W5100
  module XILINX_EMACLITE
  module XILINX_LL_TEMAC
  # drivers/net/ieee802154
  module IEEE802154_ADF7242
  module IEEE802154_AT86RF230
  module IEEE802154_ATUSB
  module IEEE802154_CA8210
  module IEEE802154_CC2520
  module IEEE802154_DRIVERS
  module IEEE802154_FAKELB
  module IEEE802154_MCR20A
  module IEEE802154_MRF24J40
  # drivers/net/mdio
  module MDIO_BCM_UNIMAC
  module MDIO_BITBANG
  module MDIO_MVUSB
  # drivers/net/phy
  module AIR_EN8811H_PHY
  module AS21XXX_PHY
  module DP83867_PHY
  module DP83TG720_PHY
  module MAXLINEAR_86110_PHY
  module QCA808X_PHY
  module QCA83XX_PHY
  module VITESSE_PHY
  module XILINX_GMII2RGMII
  # drivers/net/ppp
  module PPP
  module PPPOATM
  module PPPOE
  module PPPOL2TP
  module PPP_ASYNC
  module PPP_BSDCOMP
  module PPP_DEFLATE
  module PPP_MPPE
  module PPP_SYNC_TTY
  module PPTP
  # drivers/net/slip
  module SLIP
  # drivers/net/team
  module NET_TEAM
  module NET_TEAM_MODE_ACTIVEBACKUP
  module NET_TEAM_MODE_BROADCAST
  module NET_TEAM_MODE_LOADBALANCE
  module NET_TEAM_MODE_RANDOM
  module NET_TEAM_MODE_ROUNDROBIN
  # drivers/net/wireless
  module ATH9K_PCI_NO_EEPROM
  module CW1200
  module CW1200_WLAN_SDIO
  module CW1200_WLAN_SPI
  module LIBERTAS_THINFIRM
  module LIBERTAS_THINFIRM_USB
  module QTNFMAC_PCIE
  module RTL8192DU
  module RTW89_8922AU
  module VIRT_WIFI
  module WCN36XX
  module WL1251
  module WL1251_SDIO
  module WL1251_SPI
  module WL12XX
  module WL18XX
  module WLCORE
  module WLCORE_SDIO
  # drivers/net/wwan
  module IOSM
  module MHI_WWAN_CTRL
  module MHI_WWAN_MBIM
  module MTK_T7XX
  module WWAN
  # drivers/nfc
  module NFC_MEI_PHY
  module NFC_MICROREAD
  module NFC_MICROREAD_MEI
  module NFC_MRVL
  module NFC_MRVL_USB
  module NFC_NXP_NCI
  module NFC_NXP_NCI_I2C
  module NFC_PN532_UART
  module NFC_PN533
  module NFC_PN533_I2C
  module NFC_PN533_USB
  module NFC_PN544
  module NFC_PN544_MEI
  module NFC_PORT100
  module NFC_SIM
  module NFC_TRF7970A
  # drivers/ntb
  module NTB_EPF
  module NTB_IDT
  module NTB_INTEL
  module NTB_PERF
  module NTB_PINGPONG
  module NTB_SWITCHTEC
  module NTB_TOOL
  # drivers/nvdimm
  module RAMDAX
  # drivers/nvme
  module NVME_RDMA
  module NVME_TARGET
  module NVME_TARGET_FC
  module NVME_TARGET_FCLOOP
  module NVME_TARGET_LOOP
  module NVME_TARGET_RDMA
  module NVME_TARGET_TCP
  # drivers/nvmem
  module NVMEM_QNAP_MCU_EEPROM
  # drivers/parport
  module PARPORT_PC
  module PARPORT_PC_PCMCIA
  module PARPORT_SERIAL
  # drivers/pci
  module PCI_PF_STUB
  module PCI_PWRCTRL_GENERIC
  module PCI_PWRCTRL_TC9563
  module PCI_SW_SWITCHTEC
  # drivers/pcmcia
  module PD6729
  # drivers/perf
  module CXL_PMU
  module DWC_PCIE_PMU
  # drivers/phy
  module PHY_NXP_TJA1145
  module PHY_TUSB1210
  # drivers/pinctrl
  module PINCTRL_CS42L43
  module PINCTRL_CY8C95X0
  module PINCTRL_LYNXPOINT
  module PINCTRL_UPBOARD
  # drivers/platform/mellanox
  module MLXREG_DPU
  # drivers/platform/x86
  module ACPI_QUICKSTART
  module ADV_SWBUTTON
  module AMD_3D_VCACHE
  module AMD_HSMP
  module AMD_HSMP_ACPI
  module AMD_HSMP_PLAT
  module AMD_ISP_PLATFORM
  module AYANEO_EC
  module BARCO_P50_GPIO
  module BITLAND_MIFS_WMI
  module DASHARO_ACPI
  module DELL_DW5826E_RESET
  module DELL_UART_BACKLIGHT
  module INSPUR_PLATFORM_PROFILE
  module INTEL_ATOMISP2_LED
  module INTEL_BXTWC_PMIC_TMU
  module INTEL_BYTCRC_PWRSRC
  module INTEL_CHTDC_TI_PWRBTN
  module INTEL_EHL_PSE_IO
  module INTEL_IFS
  module INTEL_ISHTP_ECLITE
  module INTEL_MRFLD_PWRBTN
  module INTEL_PLR_TPMI
  module INTEL_PMT_CRASHLOG
  module INTEL_PUNIT_IPC
  module INTEL_SAR_INT1092
  module INTEL_SCU_IPC_UTIL
  module INTEL_SCU_PLATFORM
  module INTEL_SDSI
  module INTEL_SPEED_SELECT_INTERFACE
  module INTEL_TELEMETRY
  module INTEL_UNCORE_FREQ_CONTROL
  module INTEL_WMI_SBL_FW_UPDATE
  module LENOVO_WMI_CAMERA
  module LENOVO_WMI_GAMEZONE
  module LENOVO_WMI_HOTKEY_UTILITIES
  module LENOVO_WMI_TUNING
  module MEEGOPAD_ANX7428
  module MSI_WMI_PLATFORM
  module OXP_EC
  module PORTWELL_EC
  module REDMI_WMI
  module SAMSUNG_GALAXYBOOK
  module SEL3350_PLATFORM
  module TUXEDO_NB04_WMI_AB
  module WINMATE_FM07_KEYS
  module YT2_1380
  # drivers/power
  module BATTERY_INTEL_DC_TI
  module BATTERY_MAX1720X
  module BATTERY_S2MU005
  module CHARGER_MAX77705
  module CHARGER_MAX8971
  module CHARGER_RT9756
  module FUEL_GAUGE_MM8013
  module FUEL_GAUGE_STC3117
  module POWER_RESET_QEMU_VIRT_CTRL
  module POWER_SEQUENCING
  # drivers/powercap
  module INTEL_RAPL_TPMI
  # drivers/pps
  module PPS_CLIENT_GPIO
  module PPS_CLIENT_LDISC
  module PPS_CLIENT_PARPORT
  module PPS_GENERATOR
  module PPS_GENERATOR_TIO
  # drivers/ptp
  module DP83640_PHY
  module PTP_1588_CLOCK_FC3W
  module PTP_1588_CLOCK_IDT82P33
  module PTP_1588_CLOCK_IDTCM
  module PTP_1588_CLOCK_VMW
  module PTP_DFL_TOD
  # drivers/pwm
  module PWM_CROS_EC
  module PWM_DWC
  module PWM_GPIO
  module PWM_LPSS_PCI
  # drivers/regulator
  module REGULATOR_ADP5055
  module REGULATOR_ARIZONA_LDO1
  module REGULATOR_ARIZONA_MICSUPP
  module REGULATOR_MAX77503
  module REGULATOR_PF9453
  module REGULATOR_RT4831
  module REGULATOR_RT5120
  module REGULATOR_RT8092
  module REGULATOR_SY7636A
  module REGULATOR_TPS65185
  module REGULATOR_TPS68470
  # drivers/reset
  module RESET_GPIO
  module RESET_TI_TPS380X
  # drivers/rtc
  module RTC_DRV_ABEOZ9
  module RTC_DRV_ABX80X
  module RTC_DRV_BQ32K
  module RTC_DRV_CROS_EC
  module RTC_DRV_DS1286
  module RTC_DRV_DS1305
  module RTC_DRV_DS1307
  module RTC_DRV_DS1343
  module RTC_DRV_DS1347
  module RTC_DRV_DS1374
  module RTC_DRV_DS1390
  module RTC_DRV_DS1511
  module RTC_DRV_DS1553
  module RTC_DRV_DS1672
  module RTC_DRV_DS1685_FAMILY
  module RTC_DRV_DS1742
  module RTC_DRV_DS2404
  module RTC_DRV_DS3232
  module RTC_DRV_EM3027
  module RTC_DRV_FM3130
  module RTC_DRV_ISL12022
  module RTC_DRV_ISL1208
  module RTC_DRV_M41T80
  module RTC_DRV_M41T93
  module RTC_DRV_M41T94
  module RTC_DRV_M48T35
  module RTC_DRV_M48T59
  module RTC_DRV_MAX31335
  module RTC_DRV_MAX6900
  module RTC_DRV_MAX6902
  module RTC_DRV_MAX6916
  module RTC_DRV_MCP795
  module RTC_DRV_MSM6242
  module RTC_DRV_PCF2123
  module RTC_DRV_PCF2127
  module RTC_DRV_PCF85063
  module RTC_DRV_PCF8523
  module RTC_DRV_PCF8563
  module RTC_DRV_PCF8583
  module RTC_DRV_R9701
  module RTC_DRV_RP5C01
  module RTC_DRV_RS5C348
  module RTC_DRV_RS5C372
  module RTC_DRV_RV3028
  module RTC_DRV_RV3029C2
  module RTC_DRV_RV3032
  module RTC_DRV_RV8803
  module RTC_DRV_RX4581
  module RTC_DRV_RX8010
  module RTC_DRV_RX8025
  module RTC_DRV_RX8581
  module RTC_DRV_SD3078
  module RTC_DRV_STK17TA8
  module RTC_DRV_TPS6594
  module RTC_DRV_X1205
  # drivers/scsi
  module BE2ISCSI
  module BLK_DEV_3W_XXXX_RAID
  module CHR_DEV_SCH
  module CHR_DEV_ST
  module FCOE
  module FCOE_FNIC
  module ISCSI_BOOT_SYSFS
  module LIBFC
  module LIBFCOE
  module MEGARAID_LEGACY
  module QEDF
  module QEDI
  module SCSI_ACARD
  module SCSI_ADVANSYS
  module SCSI_BFA_FC
  module SCSI_BNX2X_FCOE
  module SCSI_BNX2_ISCSI
  module SCSI_CHELSIO_FCOE
  module SCSI_CXGB3_ISCSI
  module SCSI_CXGB4_ISCSI
  module SCSI_DC395x
  module SCSI_DEBUG
  module SCSI_DMX3191D
  module SCSI_EFCT
  module SCSI_ENCLOSURE
  module SCSI_FC_ATTRS
  module SCSI_FDOMAIN_PCI
  module SCSI_HPTIOP
  module SCSI_INIA100
  module SCSI_INITIO
  module SCSI_IPR
  module SCSI_IPS
  module SCSI_LPFC
  module SCSI_MPI3MR
  module SCSI_MPT2SAS
  module SCSI_MVUMI
  module SCSI_MYRB
  module SCSI_MYRS
  module SCSI_PMCRAID
  module SCSI_QLA_FC
  module SCSI_QLA_ISCSI
  module SCSI_QLOGIC_1280
  module SCSI_SNIC
  module SCSI_SRP_ATTRS
  module SCSI_SYM53C8XX_2
  module SCSI_WD719X
  module TCM_QLA2XXX
  # drivers/soc
  module WPCM450_SOC
  # drivers/soundwire
  module SOUNDWIRE_AMD
  # drivers/spi
  module SPI_ALTERA_CORE
  module SPI_ALTERA_DFL
  module SPI_CH341
  module SPI_CS42L43
  module SPI_DLN2
  module SPI_INTEL
  module SPI_INTEL_PCI
  module SPI_LJCA
  module SPI_MICROCHIP_CORE_QSPI
  module SPI_MUX
  module SPI_OFFLOAD_TRIGGER_PWM
  module SPI_PCI1XXXX
  module SPI_SPIDEV
  module SPI_VIRTIO
  # drivers/staging
  module RTL8723BS
  module VIDEO_IPU3_IMGU
  # drivers/target
  module ISCSI_TARGET
  module ISCSI_TARGET_CXGB4
  module LOOPBACK_TARGET
  module REMOTE_TARGET
  module SBP_TARGET
  module TCM_FC
  module TCM_FILEIO
  module TCM_IBLOCK
  module TCM_PSCSI
  module TCM_USER2
  # drivers/thermal
  module INT3406_THERMAL
  module INT340X_THERMAL
  module INTEL_BXT_PMIC_THERMAL
  module INTEL_PCH_THERMAL
  module INTEL_POWERCLAMP
  module INTEL_SOC_DTS_THERMAL
  module INTEL_TCC_COOLING
  # drivers/thunderbolt
  module USB4_STREAM
  # drivers/tty
  module IPWIRELESS
  module NOZOMI
  module NULL_TTY
  module N_HDLC
  module SERIAL_8250_DFL
  module SERIAL_ARC
  module SERIAL_JSM
  module SERIAL_SC16IS7XX
  module SERIAL_SC16IS7XX_I2C
  module SERIAL_SC16IS7XX_SPI
  # drivers/ufs
  module SCSI_UFSHCD
  module SCSI_UFSHCD_PCI
  module SCSI_UFSHCD_PLATFORM
  module SCSI_UFS_CDNS_PLATFORM
  # drivers/uio
  module UIO_DFL
  module UIO_HV_GENERIC
  module UIO_PCI_GENERIC
  # drivers/usb/atm
  module USB_ATM
  module USB_CXACRU
  module USB_SPEEDTOUCH
  module USB_UEAGLEATM
  module USB_XUSBATM
  # drivers/usb/cdns3
  module USB_CDNS3
  module USB_CDNS3_PCI_WRAP
  module USB_CDNSP_PCI
  module USB_CDNS_SUPPORT
  # drivers/usb/class
  module USB_TMC
  # drivers/usb/common
  module USB_ULPI_BUS
  # drivers/usb/core
  module USB_LEDS_TRIGGER_USBPORT
  # drivers/usb/dwc3
  module USB_DWC3
  module USB_DWC3_PCI
  # drivers/usb/gadget
  module USB_CDNS2_UDC
  module USB_GADGET
  module USB_MAX3420_UDC
  # drivers/usb/host
  module USB_SL811_HCD
  module USB_XHCI_PLATFORM
  # drivers/usb/image
  module USB_MDC800
  module USB_MICROTEK
  # drivers/usb/misc
  module USB_ADUTUX
  module USB_APPLEDISPLAY
  module USB_CHAOSKEY
  module USB_EMI26
  module USB_EMI62
  module USB_HSIC_USB3503
  module USB_HSIC_USB4604
  module USB_HUB_USB251XB
  module USB_IDMOUSE
  module USB_IOWARRIOR
  module USB_ISIGHTFW
  module USB_LCD
  module USB_LD
  module USB_LEGOTOWER
  module USB_LJCA
  module USB_SEVSEG
  module USB_SISUSBVGA
  module USB_TRANCEVIBRATOR
  module USB_USBIO
  module USB_USS720
  module USB_YUREX
  # drivers/usb/phy
  module NOP_USB_XCEIV
  # drivers/usb/serial
  module USB_SERIAL_F81232
  # drivers/usb/storage
  module USB_STORAGE_ALAUDA
  module USB_STORAGE_CYPRESS_ATACB
  module USB_STORAGE_DATAFAB
  module USB_STORAGE_ENE_UB6250
  module USB_STORAGE_FREECOM
  module USB_STORAGE_ISD200
  module USB_STORAGE_JUMPSHOT
  module USB_STORAGE_KARMA
  module USB_STORAGE_ONETOUCH
  module USB_STORAGE_REALTEK
  module USB_STORAGE_SDDR09
  module USB_STORAGE_SDDR55
  module USB_STORAGE_USBAT
  # drivers/usb/typec
  module TYPEC_HD3SS3220
  module TYPEC_MUX_FSA4480
  module TYPEC_MUX_GPIO_SBU
  module TYPEC_MUX_INTEL_PMC
  module TYPEC_MUX_IT5205
  module TYPEC_MUX_NB7VPQ904M
  module TYPEC_MUX_PS883X
  module TYPEC_MUX_TUSB1046
  module TYPEC_RT1719
  module TYPEC_STUSB160X
  module TYPEC_TBT_ALTMODE
  module TYPEC_TCPCI
  module TYPEC_TCPCI_MAXIM
  module TYPEC_WCOVE
  module TYPEC_WUSB3801
  module UCSI_ACPI
  module UCSI_CCG
  module UCSI_STM32G0
  # drivers/usb/usbip
  module USBIP_CORE
  module USBIP_HOST
  module USBIP_VHCI_HCD
  module USBIP_VUDC
  # drivers/vdpa
  module ALIBABA_ENI_VDPA
  module IFCVF
  module MLX5_VDPA_NET
  module OCTEONEP_VDPA
  module PDS_VDPA
  module SNET_VDPA
  module VDPA_SIM
  module VDPA_SIM_BLOCK
  module VDPA_SIM_NET
  module VP_VDPA
  # drivers/vfio
  module MLX5_VFIO_PCI
  module PDS_VFIO_PCI
  module QAT_VFIO_PCI
  module VFIO_MDEV
  module XE_VFIO_PCI
  # drivers/video
  module BACKLIGHT_APPLE
  module BACKLIGHT_ARCXCNN
  module BACKLIGHT_AW99706
  module BACKLIGHT_KTD253
  module BACKLIGHT_KTZ8866
  module BACKLIGHT_LM3509
  module BACKLIGHT_LP855X
  module BACKLIGHT_MAX25014
  module BACKLIGHT_MP3309C
  module BACKLIGHT_PWM
  module BACKLIGHT_RT4831
  module LCD_CLASS_DEVICE
  module LCD_PLATFORM
  # drivers/virt
  module EFI_SECRET
  module NITRO_ENCLAVES
  # drivers/virtio
  module VIRTIO_RTC
  # drivers/w1
  module W1
  module W1_MASTER_DS2482
  module W1_MASTER_DS2490
  module W1_MASTER_UART
  module W1_SLAVE_DS2405
  module W1_SLAVE_DS2406
  module W1_SLAVE_DS2408
  module W1_SLAVE_DS2413
  module W1_SLAVE_DS2423
  module W1_SLAVE_DS2430
  module W1_SLAVE_DS2431
  module W1_SLAVE_DS2433
  module W1_SLAVE_DS2438
  module W1_SLAVE_DS2780
  module W1_SLAVE_DS2781
  module W1_SLAVE_DS2805
  module W1_SLAVE_DS28E04
  module W1_SLAVE_SMEM
  module W1_SLAVE_THERM
  # drivers/watchdog
  module ADVANTECH_EC_WDT
  module ALIM1535_WDT
  module ALIM7101_WDT
  module CGBC_WDT
  module CROS_EC_WATCHDOG
  module EXAR_WDT
  module F71808E_WDT
  module HP_WATCHDOG
  module I6300ESB_WDT
  module IB700_WDT
  module IBMASR
  module IE6XX_WDT
  module INTEL_MEI_WDT
  module INTEL_OC_WATCHDOG
  module IT8712F_WDT
  module IT87_WDT
  module ITCO_WDT
  module LENOVO_SE10_WDT
  module LENOVO_SE30_WDT
  module MLX_WDT
  module NIC7018_WDT
  module NV_TCO
  module PCIPCWATCHDOG
  module SBC_FITPC2_WATCHDOG
  module SMSC_SCH311X_WDT
  module SOFT_WATCHDOG
  module SP5100_TCO
  module TQMX86_WDT
  module USBPCWATCHDOG
  module VIA_WDT
  module W83627HF_WDT
  module W83877F_WDT
  module W83977F_WDT
  module WDAT_WDT
  module WDTPCI
  # drivers/xen
  module XEN_SCSI_BACKEND
  # fs/affs
  module AFFS_FS
  # fs/afs
  module AFS_FS
  # fs/befs
  module BEFS_FS
  # fs/cachefiles
  module CACHEFILES
  # fs/ceph
  module CEPH_FS
  # fs/coda
  module CODA_FS
  # fs/dlm
  module DLM
  # fs/ecryptfs
  module ECRYPT_FS
  # fs/gfs2
  module GFS2_FS
  # fs/hfs
  module HFS_FS
  # fs/hfsplus
  module HFSPLUS_FS
  # fs/jffs2
  module JFFS2_FS
  # fs/jfs
  module JFS_FS
  # fs/minix
  module MINIX_FS
  # fs/nilfs2
  module NILFS2_FS
  # fs/nls
  module NLS_CODEPAGE_1250
  module NLS_CODEPAGE_1251
  module NLS_CODEPAGE_737
  module NLS_CODEPAGE_775
  module NLS_CODEPAGE_850
  module NLS_CODEPAGE_852
  module NLS_CODEPAGE_855
  module NLS_CODEPAGE_857
  module NLS_CODEPAGE_860
  module NLS_CODEPAGE_861
  module NLS_CODEPAGE_862
  module NLS_CODEPAGE_863
  module NLS_CODEPAGE_864
  module NLS_CODEPAGE_865
  module NLS_CODEPAGE_866
  module NLS_CODEPAGE_869
  module NLS_CODEPAGE_874
  module NLS_CODEPAGE_932
  module NLS_CODEPAGE_936
  module NLS_CODEPAGE_949
  module NLS_CODEPAGE_950
  module NLS_ISO8859_13
  module NLS_ISO8859_14
  module NLS_ISO8859_15
  module NLS_ISO8859_2
  module NLS_ISO8859_3
  module NLS_ISO8859_4
  module NLS_ISO8859_5
  module NLS_ISO8859_6
  module NLS_ISO8859_7
  module NLS_ISO8859_8
  module NLS_ISO8859_9
  module NLS_KOI8_R
  module NLS_KOI8_U
  module NLS_MAC_CELTIC
  module NLS_MAC_CENTEURO
  module NLS_MAC_CROATIAN
  module NLS_MAC_CYRILLIC
  module NLS_MAC_GAELIC
  module NLS_MAC_GREEK
  module NLS_MAC_ICELAND
  module NLS_MAC_INUIT
  module NLS_MAC_ROMAN
  module NLS_MAC_ROMANIAN
  module NLS_MAC_TURKISH
  # fs/ntfs
  module NTFS_FS
  # fs/ocfs2
  module OCFS2_FS
  module OCFS2_FS_O2CB
  module OCFS2_FS_USERSPACE_CLUSTER
  # fs/orangefs
  module ORANGEFS_FS
  # fs/pstore
  module PSTORE_RAM
  # fs/romfs
  module ROMFS_FS
  # fs/ubifs
  module UBIFS_FS
  # fs/ufs
  module UFS_FS
  # init
  module IKHEADERS
  # kernel/trace
  module RING_BUFFER_BENCHMARK
  # lib
  module PARMAN
  # lib/math
  module PRIME_NUMBERS
  # mm
  module HWPOISON_INJECT
  # net/6lowpan
  module 6LOWPAN_GHC_EXT_HDR_DEST
  module 6LOWPAN_GHC_EXT_HDR_FRAG
  module 6LOWPAN_GHC_EXT_HDR_HOP
  module 6LOWPAN_GHC_EXT_HDR_ROUTE
  module 6LOWPAN_GHC_ICMPV6
  module 6LOWPAN_GHC_UDP
  # net/9p
  module NET_9P_RDMA
  module NET_9P_USBG
  module NET_9P_XEN
  # net/atm
  module ATM
  module ATM_BR2684
  # net/batman-adv
  module BATMAN_ADV
  # net/bridge
  module BRIDGE_EBT_802_3
  module BRIDGE_EBT_AMONG
  module BRIDGE_EBT_ARP
  module BRIDGE_EBT_ARPREPLY
  module BRIDGE_EBT_BROUTE
  module BRIDGE_EBT_DNAT
  module BRIDGE_EBT_IP
  module BRIDGE_EBT_IP6
  module BRIDGE_EBT_LIMIT
  module BRIDGE_EBT_LOG
  module BRIDGE_EBT_MARK
  module BRIDGE_EBT_MARK_T
  module BRIDGE_EBT_NFLOG
  module BRIDGE_EBT_PKTTYPE
  module BRIDGE_EBT_REDIRECT
  module BRIDGE_EBT_SNAT
  module BRIDGE_EBT_STP
  module BRIDGE_EBT_T_FILTER
  module BRIDGE_EBT_T_NAT
  module BRIDGE_EBT_VLAN
  module BRIDGE_NF_EBTABLES
  module BRIDGE_NF_EBTABLES_LEGACY
  module NFT_BRIDGE_META
  module NFT_BRIDGE_REJECT
  # net/ceph
  module CEPH_LIB
  # net/dsa
  module NET_DSA
  module NET_DSA_TAG_GSWIP
  module NET_DSA_TAG_HELLCREEK
  module NET_DSA_TAG_KSZ
  module NET_DSA_TAG_MXL_862XX
  module NET_DSA_TAG_NETC
  module NET_DSA_TAG_OCELOT
  module NET_DSA_TAG_OCELOT_8021Q
  module NET_DSA_TAG_RTL4_A
  module NET_DSA_TAG_RTL8_4
  module NET_DSA_TAG_SJA1105
  module NET_DSA_TAG_TRAILER
  module NET_DSA_TAG_XRS700X
  # net/hsr
  module HSR
  # net/ieee802154
  module IEEE802154
  module IEEE802154_6LOWPAN
  module IEEE802154_SOCKET
  # net/ife
  module NET_IFE
  # net/ipv4
  module INET_AH
  module INET_ESP
  module INET_ESP_OFFLOAD
  module INET_IPCOMP
  module NET_FOU
  module NET_IPGRE
  module NET_IPGRE_DEMUX
  module NET_IPIP
  module NET_IPVTI
  module TCP_CONG_BBR
  module TCP_CONG_BIC
  module TCP_CONG_CDG
  module TCP_CONG_DCTCP
  module TCP_CONG_HSTCP
  module TCP_CONG_HTCP
  module TCP_CONG_HYBLA
  module TCP_CONG_ILLINOIS
  module TCP_CONG_LP
  module TCP_CONG_NV
  module TCP_CONG_SCALABLE
  module TCP_CONG_VEGAS
  module TCP_CONG_VENO
  module TCP_CONG_WESTWOOD
  module TCP_CONG_YEAH
  # net/ipv6
  module INET6_ESP_OFFLOAD
  module INET6_IPCOMP
  module IPV6_GRE
  module IPV6_ILA
  module IPV6_TUNNEL
  module IPV6_VTI
  # net/kcm
  module AF_KCM
  # net/l2tp
  module L2TP
  module L2TP_DEBUGFS
  # net/mac802154
  module MAC802154
  # net/mpls
  module MPLS_IPTUNNEL
  module MPLS_ROUTING
  module NET_MPLS_GSO
  # net/netfilter
  module IP_VS_DH
  module IP_VS_FO
  module IP_VS_LBLC
  module IP_VS_LBLCR
  module IP_VS_LC
  module IP_VS_MH
  module IP_VS_NQ
  module IP_VS_OVF
  module IP_VS_RR
  module IP_VS_SED
  module IP_VS_SH
  module IP_VS_TWOS
  module IP_VS_WLC
  module IP_VS_WRR
  module NETFILTER_NETLINK_HOOK
  module NETFILTER_XT_TARGET_NOTRACK
  module NFT_OSF
  module NFT_REJECT_NETDEV
  module NFT_XFRM
  # net/nfc
  module NFC
  module NFC_DIGITAL
  module NFC_HCI
  module NFC_NCI
  module NFC_NCI_SPI
  # net/nsh
  module NET_NSH
  # net/openvswitch
  module OPENVSWITCH
  module OPENVSWITCH_GENEVE
  module OPENVSWITCH_GRE
  module OPENVSWITCH_VXLAN
  # net/psample
  module PSAMPLE
  # net/rds
  module RDS
  module RDS_RDMA
  module RDS_TCP
  # net/rfkill
  module RFKILL_GPIO
  # net/rxrpc
  module AF_RXRPC
  # net/sched
  module NET_ACT_BPF
  module NET_ACT_CONNMARK
  module NET_ACT_CT
  module NET_ACT_CTINFO
  module NET_ACT_GACT
  module NET_ACT_GATE
  module NET_ACT_IFE
  module NET_ACT_MIRRED
  module NET_ACT_MPLS
  module NET_ACT_NAT
  module NET_ACT_PEDIT
  module NET_ACT_SAMPLE
  module NET_ACT_SIMP
  module NET_ACT_SKBEDIT
  module NET_ACT_SKBMOD
  module NET_ACT_TUNNEL_KEY
  module NET_ACT_VLAN
  module NET_CLS_BASIC
  module NET_CLS_BPF
  module NET_CLS_FLOW
  module NET_CLS_FLOWER
  module NET_CLS_MATCHALL
  module NET_CLS_ROUTE4
  module NET_EMATCH_CMP
  module NET_EMATCH_IPSET
  module NET_EMATCH_IPT
  module NET_EMATCH_META
  module NET_EMATCH_NBYTE
  module NET_EMATCH_TEXT
  module NET_EMATCH_U32
  module NET_IFE_SKBMARK
  module NET_IFE_SKBPRIO
  module NET_IFE_SKBTCINDEX
  module NET_SCH_CAKE
  module NET_SCH_CBS
  module NET_SCH_CHOKE
  module NET_SCH_CODEL
  module NET_SCH_DRR
  module NET_SCH_DUALPI2
  module NET_SCH_ETF
  module NET_SCH_ETS
  module NET_SCH_FQ
  module NET_SCH_FQ_PIE
  module NET_SCH_GRED
  module NET_SCH_HFSC
  module NET_SCH_HHF
  module NET_SCH_MQPRIO
  module NET_SCH_MULTIQ
  module NET_SCH_NETEM
  module NET_SCH_PIE
  module NET_SCH_PLUG
  module NET_SCH_PRIO
  module NET_SCH_QFQ
  module NET_SCH_RED
  module NET_SCH_SFB
  module NET_SCH_TAPRIO
  module NET_SCH_TBF
  module NET_SCH_TEQL
  # net/sctp
  module IP_SCTP
  # net/smc
  module SMC
  module SMC_DIAG
  # net/sunrpc
  module SUNRPC_XPRT_RDMA
  # net/tipc
  module TIPC
  module TIPC_DIAG
  # net/tls
  module TLS
  # net/xfrm
  module NET_KEY
  module XFRM_INTERFACE
  module XFRM_IPTFS
  # sound/core
  module SND_DMAENGINE_PCM
  # sound/hda
  module SND_HDA_ACPI
  # sound/soc
  module SND_DESIGNWARE_I2S
  module SND_SIMPLE_CARD
  module SND_SIMPLE_CARD_UTILS
  module SND_SOC_AC97_CODEC
  module SND_SOC_ADAU1373
  module SND_SOC_ADAU1761_I2C
  module SND_SOC_ADAU1761_SPI
  module SND_SOC_ADAU7118_HW
  module SND_SOC_ADAU7118_I2C
  module SND_SOC_ADI_AXI_I2S
  module SND_SOC_ADI_AXI_SPDIF
  module SND_SOC_AK4619
  module SND_SOC_AK5558
  module SND_SOC_AMD_ACP7X
  module SND_SOC_AMD_LEGACY_SDW_MACH
  module SND_SOC_AMD_SOF_SDW_MACH
  module SND_SOC_AMD_SOUNDWIRE
  module SND_SOC_AMD_ST_ES8336_MACH
  module SND_SOC_AUDIO_IIO_AUX
  module SND_SOC_AW8738
  module SND_SOC_AW87390
  module SND_SOC_AW88081
  module SND_SOC_AW88166
  module SND_SOC_AW88261
  module SND_SOC_AW88395
  module SND_SOC_AW88399
  module SND_SOC_BD28623
  module SND_SOC_BT_SCO
  module SND_SOC_CHV3_CODEC
  module SND_SOC_CHV3_I2S
  module SND_SOC_CS35L34
  module SND_SOC_CS35L35
  module SND_SOC_CS35L36
  module SND_SOC_CS35L45_I2C
  module SND_SOC_CS35L45_SPI
  module SND_SOC_CS40L50
  module SND_SOC_CS4234
  module SND_SOC_CS42L83
  module SND_SOC_CS42L84
  module SND_SOC_CS43130
  module SND_SOC_CS48L32
  module SND_SOC_CS530X_I2C
  module SND_SOC_CS530X_SPI
  module SND_SOC_ES7134
  module SND_SOC_ES8311
  module SND_SOC_ES8323
  module SND_SOC_ES8328
  module SND_SOC_ES8328_I2C
  module SND_SOC_ES8328_SPI
  module SND_SOC_ES8375
  module SND_SOC_ES8389
  module SND_SOC_IDT821034
  module SND_SOC_INTEL_AVS_MACH_ES8336
  module SND_SOC_INTEL_AVS_MACH_MAX98357A
  module SND_SOC_INTEL_AVS_MACH_PCM3168A
  module SND_SOC_INTEL_AVS_MACH_PROBE
  module SND_SOC_INTEL_AVS_MACH_RT274
  module SND_SOC_INTEL_AVS_MACH_RT298
  module SND_SOC_INTEL_AVS_MACH_RT5640
  module SND_SOC_INTEL_AVS_MACH_RT5682
  module SND_SOC_INTEL_BYT_CHT_NOCODEC_MACH
  module SND_SOC_INTEL_EHL_RT5660_MACH
  module SND_SOC_INTEL_SOF_PCM512x_MACH
  module SND_SOC_INTEL_SOF_WM8804_MACH
  module SND_SOC_MAX9759
  module SND_SOC_MAX98088
  module SND_SOC_MAX98396
  module SND_SOC_MAX98520
  module SND_SOC_MAX9867
  module SND_SOC_MT6357
  module SND_SOC_NAU8540
  module SND_SOC_NTP8835
  module SND_SOC_NTP8918
  module SND_SOC_PCM1754
  module SND_SOC_PCM1789_I2C
  module SND_SOC_PCM186X_I2C
  module SND_SOC_PCM186X_SPI
  module SND_SOC_PCM3060_I2C
  module SND_SOC_PCM3060_SPI
  module SND_SOC_PCM3168A_I2C
  module SND_SOC_PCM512x
  module SND_SOC_PCM512x_I2C
  module SND_SOC_PCM6240
  module SND_SOC_PM4125_SDW
  module SND_SOC_RT1017_SDCA_SDW
  module SND_SOC_RT5575
  module SND_SOC_RT5659
  module SND_SOC_RT5660
  module SND_SOC_RT9123
  module SND_SOC_RT9123P
  module SND_SOC_RTQ9124
  module SND_SOC_RTQ9128
  module SND_SOC_SDCA_CLASS
  module SND_SOC_SIMPLE_AMPLIFIER
  module SND_SOC_SIMPLE_MUX
  module SND_SOC_SMA1303
  module SND_SOC_SMA1307
  module SND_SOC_SOF_ACPI
  module SND_SOC_SOF_AMD_ACP63
  module SND_SOC_SOF_AMD_SOUNDWIRE
  module SND_SOC_SOF_AMD_VANGOGH
  module SND_SOC_SOF_BAYTRAIL
  module SND_SOC_SOF_BROADWELL
  module SND_SOC_SPDIF
  module SND_SOC_TAC5XX2_SDW
  module SND_SOC_TAS2562
  module SND_SOC_TAS2764
  module SND_SOC_TAS2770
  module SND_SOC_TAS2780
  module SND_SOC_TAS2783_SDW
  module SND_SOC_TAS5805M
  module SND_SOC_TAS6424
  module SND_SOC_TAS675X
  module SND_SOC_TDA7419
  module SND_SOC_TLV320ADC3XXX
  module SND_SOC_TLV320ADCX140
  module SND_SOC_TLV320AIC32X4_I2C
  module SND_SOC_TLV320AIC32X4_SPI
  module SND_SOC_TSCS42XX
  module SND_SOC_UDA1342
  module SND_SOC_UDA1380
  module SND_SOC_WCD937X_SDW
  module SND_SOC_WCD939X_SDW
  module SND_SOC_WM8524
  module SND_SOC_WM8731
  module SND_SOC_WM8731_I2C
  module SND_SOC_WM8731_SPI
  module SND_SOC_WM8804
  module SND_SOC_WM8804_I2C
  module SND_SOC_WM8940
  module SND_SOC_WM8961
  module SND_SOC_WSA883X
  module SND_SOC_WSA884X
  module SND_SOC_ZL38060
  # sound/usb
  module SND_USB_US144MKII
fi
