name: issue and PR lifecycle

on:
  issues:
    types: [opened, labeled, closed]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  schedule:
    - cron: '0 9 * * *'

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  lifecycle:
    uses: projectbluefin/bonedigger/.github/workflows/lifecycle.yml@7f2875210d89a170858f962cd6a089d4a813f214 # require diagnostic Gists
    with:
      brand_name: "Dakota"
    secrets: inherit
