name: issue and PR lifecycle

on:
  issues:
    types: [opened, labeled, closed]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  schedule:
    - cron: '0 9 * * *'

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  lifecycle:
    uses: projectbluefin/bonedigger/.github/workflows/lifecycle.yml@03f32c481d0c435606a5f0fc2745e7116d70bbaa # require diagnostic Gists
    with:
      brand_name: "Dakota"
    secrets: inherit
