name: Cleanup Old Images
on:
  schedule:
    - cron: "15 0 * * 0" # 0015 UTC on Sundays
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: projectbluefin/actions/bootc-build/ghcr-cleanup@2a09e72e9be15b137392dde15f8587f35587e8eb # feat/ghcr-cleanup-orphaned-images
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          packages: dakota,dakota-nvidia
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7
